#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# fossensics-br2 - Collect FOSS information from a Buildroot build
#
# Copyright (c) 2013 Eric Le Bihan <eric.le.bihan.dev@free.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import argparse
from fossensics import __version__, setup_i18n
from fossensics.buildroot2 import Inspector, format_statistics
from gettext import gettext as _

setup_i18n()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--version',
                        action='version',
                        version=__version__)
    parser.add_argument('builddir',
                        help=_('build directory'))
    parser.add_argument('-o', '--output',
                        metavar='DIR',
                        help=_('set output directory'))
    parser.add_argument('--stats', '-s',
                        dest='show_stats',
                        action='store_true',
                        default=False,
                        help=_('display statistics when finished'))

    args = parser.parse_args()

    output = args.output
    if not output:
        output = os.path.join(os.getcwd(), 'output')

    inspector = Inspector(args.builddir)
    inspector.inspect(output)
    if args.show_stats:
        format_statistics(inspector.statistics)

# vim: ts=4 sts=4 sw=4 et ai
